Repository drews54/Discord-Music-Bot, pull requests merged in 2021-03, with the labels that each got.

#47 Implement volume control #6
  cogs/music.py
Labels: enhancement

#53 The volume is not too high on values over 20% anymore
  cogs/music.py
Labels: bug, enhancement

#55 piunov1998/issue54
  cogs/music.py
Labels: enhancement

#56 Localization
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  bot.py
  cogs/music.py
  locale/en/LC_MESSAGES/Discord-Music-Bot.po
  locale/ru/LC_MESSAGES/Discord-Music-Bot.po
  start.bat
  start.ps1
  start.sh
Labels: enhancement, help wanted

#57 Play reformation
  cogs/music.py
Labels: enhancement
